# Generated by Django 4.0.4 on 2022-06-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_alter_entradas_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradas',
            name='img',
        ),
    ]
