# Generated by Django 4.0.4 on 2022-07-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0003_remove_entradas_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradas',
            options={'verbose_name': 'entrada', 'verbose_name_plural': 'entradas'},
        ),
    ]
