# Generated by Django 4.0.4 on 2022-07-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bebidas',
            options={'verbose_name': 'bebida', 'verbose_name_plural': 'bebidas'},
        ),
    ]
