# Generated by Django 4.0.4 on 2022-07-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comidas',
            options={'verbose_name': 'comida', 'verbose_name_plural': 'comidas'},
        ),
    ]
