# Generated by Django 4.0.4 on 2022-07-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('asunto', models.CharField(blank=True, max_length=30, null=True)),
                ('mensaje', models.TextField(blank=True, max_length=600, null=True)),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
            },
        ),
    ]
