# Generated by Django 4.0.4 on 2022-07-06 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_alter_user_profile_options_user_profile_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='imagen',
            new_name='foto_de_perfil',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
